### ISSUE TITLE
Passport_social fails in DE 3.1.4

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/docker-oxPassport#1]
Steps:
1. Go to Configuration Manage -> Custom scripts -> Person Authentication
2. Enable u2f, passport_social and basic_lock
3. Go to UMA RPT Policies and enable scim_access_policy
4. Go to Manage Authentication -> Passport Authentication Method and enable Passport Support
5. Add a GitHub strategy with requestForEmail set to true
6. Change the Default Authentication Method to passport_social
7. In the 2nd step of login give the natt.tester@gmail.com email

Expected: The user’s able to log in.
Actual: The user’s unable to log in, there’s a message about invalid credentials on the login screen.
[passport.log](https://github.com/GluuFederation/oxAuth/files/2462851/passport.log)
[oxauth.logs.tar.gz](https://github.com/GluuFederation/oxAuth/files/2462876/oxauth.logs.tar.gz)

**Comment by willow9886** [comment]
Utilized GitHub's new issue feature to move this over to the proper repo.

**Comment by iromli** [comment]
v3.1.4 is EOL.
